### ISSUE TITLE
Parse user not being updated correctly with venueId

### ISSUE THREAD

**Issue by anujacharya1** [TeamCinder/Cinder#4]
{
"_id": "IgOxX0sGFq",
"selfie": "",
"lastName": "Fulton",
"username": "lawson",
"phone": "650-253-0000",
"email": "lawson0.4892965723214324@example.com",
"foursquareId": "164596399",
"blurb": "Hello!",
"firstName": "Lawson",
"venueId": "4c253819c11dc9b634d82624",
"_updated_at": {
"$date": "2016-03-07T05:26:07.905Z"
},
"_created_at": {
"$date": "2016-03-06T01:52:18.238Z"
},
"_hashed_password": "$2a$10$Wx8jgB50FiO60D1TluoKDe.Lwdd888vTGbSmHX6TQ6uKAaW2fXQMS",
"venueid": "3fd66200f964a52041ee1ee3",
"selfie_file": "8a36b79b5d298b7caece749dae03bcc0_picturePath"
}

**Comment by zero-impact** [comment]
This is just an artifact from the first time I ran the code. It was already fixed:
`currentUser.put("venueId", venue.getId());`
